baseURL = "https://blog.morio.dev/"
theme = "robust"
languageCode = "en-us"
title = "backad"
enableEmoji = true
hasCJKLanguage = true
paginate = 6
enableHighlight = true
PygmentsCodeFences = true
googleAnalytics = "G-0B3L2MK54P"
ignoreErrors = ["error-remote-getjson"]

[permalinks]
  posts = "/:year/:month/:filename/"

[params]
customCSS = "css/custom.css"
enableMathJax = true

[params.author]
thumbnail = "icon.jpg"
name = "morioprog"
description = "競技プログラミングをしています。<br />最近はぷよぷよAIに興味があります。"
twitter = "https://twitter.com/morio_prog"
github = "https://github.com/morioprog"
info = "/about"
